language: node_js

node_js:
  - stable
  - 5.0
  - 4.0

before_install:
  - phantomjs --version

before_script:
  - npm install -g grunt-cli

branches:
  only:
    - master
    - dev
    - pattern-engines
    - dev-2.0-core

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a14f537f16b0756d9470
    on_success: always
    on_failure: always
    on_start: never
